import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import stdLibBrowser from 'node-stdlib-browser';
import plugin from 'node-stdlib-browser/helpers/esbuild/plugin';
import { createRequire } from 'module';

const require = createRequire(import.meta.url);

const banner =
	`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	inject: [require.resolve('node-stdlib-browser/helpers/esbuild/shim')],
	define: {
		'global': 'globalThis',
		'process.env.NODE_ENV': '"development"',
		'Buffer': 'Buffer',
	},
	platform: 'browser',
	mainFields: ['browser', 'module', 'main'],
	plugins: [
		// Handle Node.js built-in modules with trailing slash
		{
			name: 'node-builtins-trailing-slash',
			setup(build) {
				// Only handle specific Node.js built-ins with trailing slash
				build.onResolve({ filter: /^(buffer|util|assert)\/$/ }, (args) => {
					const moduleName = args.path.slice(0, -1);
					return build.resolve(moduleName, {
						kind: args.kind,
						resolveDir: args.resolveDir,
					});
				});
			},
		},
		plugin(stdLibBrowser),
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}